DROP TABLE IF EXISTS  CASCADE;
CREATE TABLE lists (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  user_id INTEGER FOREIGN KEY REFERENCES users(id) ON DELETE CASCADE
  category_id INTEGER FOREIGN KEY REFERENCES categories(id) ON DELETE CASCADE
);
